### ISSUE TITLE
add support for installing extra packages to pylint virtualenv

### ISSUE THREAD

**Issue by dupuy** [pre-commit/mirrors-pylint#3]
In order for pylint to run correctly on some of my source code, I need to install extra packages (via pip).  I have these installed in my current virtualenv, but since pre-commit (wisely) uses its own virtualenv it doesn't get anything that isn't in the requirements.txt of pylint itself.

I could play some tricky games (providing absolute path of virtualenv python) with `language_version` here to (try to?) force pre-commit to run in that virtualenv, or dig through the random scraps in my $HOME/.pre-commit directory to find the pylint virtualenv and manually install the extra stuff there, but none of that will work for another user, who would need to tweak things again themselves.

It would be really nice if the pylint pre-commit plugin could parse something in the YAML file that was a list of additional packages to be installed with pip (or maybe just `-r req-file.txt`?).  I suspect this would require additional support from pre-commit as well as extra support in the plugin, curious how you'd like to see that work before I run off and try to implement it.

**Comment by asottile** [comment]
So the thing with pylint is it does *dynamic* analysis along with *static* analysis.  It really only works correctly if it can import your code.  Basically for pylint's output to be correct it needs to be in the same context as your code would run (your app's virtualenv for instance).

pre-commit by design makes isolated virtual environments, so activating the repository specific virtualenv  (as well as installing app-specific dependencies into the isolated virtualenv) violates that.

The way we've worked around this, both for pylint and for some (admittedly icky) private hooks is to do something like this:

https://github.com/Yelp/venv-update/blob/a5960acab7101a1e70c57945b2038fef9d005aed/.pre-commit-config.yaml#L15-L22

There's a better way than the syntax used there via (not yet well documented) local hooks: https://github.com/pre-commit/pre-commit/pull/226

**Comment by asottile** [comment]
This is now supported through `additional_dependencies`: http://pre-commit.com/#plugins

**Comment by asottile** [comment]
local hooks are now documented here: http://pre-commit.com/#repository-local-hooks
